# Generated by Django 5.2.7 on 2025-11-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_nom", models.CharField(max_length=40)),
                ("patient_prenom", models.CharField(max_length=30)),
                (
                    "patient_genre",
                    models.CharField(
                        choices=[("F", "Femme"), ("H", "Homme")], max_length=1
                    ),
                ),
                ("patient_age", models.IntegerField()),
                ("description", models.TextField()),
                ("date_consultation", models.DateField()),
            ],
        ),
    ]
