# Generated by Django 5.2.6 on 2025-11-06 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=40)),
                ('quantite', models.IntegerField()),
                ('contenant', models.CharField(max_length=20)),
                ('duree', models.IntegerField()),
                ('effects_secondaires', models.TextField(blank=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.consultation')),
            ],
        ),
    ]
