# Generated by Django 4.2.26 on 2025-11-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_traitement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('speciality', models.CharField(choices=[('Gynécologue', 'Gynécologue'), ('Médecin généraliste', 'Médecin généraliste'), ('Cardiologue', 'Cardiologue'), ('Pédiatre', 'Pédiatre'), ('Dermatologue', 'Dermatologue'), ('Ophtalmologue', 'Ophtalmologue'), ('Orthopédiste', 'Orthopédiste'), ('Neurologue', 'Neurologue'), ('Psychiatre', 'Psychiatre'), ('Radiologue', 'Radiologue'), ('Chirurgien', 'Chirurgien'), ('Gastro-entérologue', 'Gastro-entérologue'), ('Rhumatologue', 'Rhumatologue'), ('Endocrinologue', 'Endocrinologue'), ('Urologue', 'Urologue'), ('Hématologue', 'Hématologue'), ('Infectiologue', 'Infectiologue')], max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=10)),
                ('start_time', models.CharField(blank=True, max_length=5)),
                ('end_time', models.CharField(blank=True, max_length=5)),
                ('available_days', models.TextField(blank=True)),
            ],
        ),
    ]
