# Generated by Django 5.2.6 on 2025-11-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_alter_doctor_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
