# Generated by Django 5.2.6 on 2025-11-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0006_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
